### ISSUE TITLE
Experiment 5: SWAY vs. MOEA

### ISSUE THREAD

**Issue by ginfung** [ai-se/RIOT#10]
Colored cell = not good in sway
Runtime
![runtime](https://user-images.githubusercontent.com/3222148/29151667-d94e6ac0-7d50-11e7-8a03-7e2e842db48b.png)

Hypervolume
![hv](https://user-images.githubusercontent.com/3222148/29151668-db913484-7d50-11e7-83c1-b4ce65239522.png)

Spread
![spread](https://user-images.githubusercontent.com/3222148/29151670-de46ec32-7d50-11e7-9c39-15987f5ff55f.png)

IGD
![igd](https://user-images.githubusercontent.com/3222148/29151671-df78cf62-7d50-11e7-8053-492920e27ff1.png)

**Comment by ginfung** [comment]
![combine](https://user-images.githubusercontent.com/3222148/29151702-0d7b7e00-7d51-11e7-96f2-b48189419ae4.png)

**Comment by timm** [comment]
so from the above, i see that

1)  SWAY is VASTLY faster than the rest
2) in the majority case, it is as good as the best (and when it fails, it fails close to the best)

how you do it? any new feature engineering? any new diversity oeprators?

**Comment by ginfung** [comment]
![image](https://user-images.githubusercontent.com/3222148/29246474-18e32084-7fc9-11e7-87af-0961cc5d70db.png)

**Comment by timm** [comment]
not seeing the intuition
prior SWAY-based work was insufficient for crowd configuration because X
hence we tried Y,Z

**Comment by ginfung** [comment]
notice that
we can treat SWAY as a simplified version of PCA -- each time we 
get principal Components->map candidates to PC-> delete half of them

SWAY fails since
1) even though sort candidates with the key PC, we can't say first, or second, half of them are unpromising. Especially in the multi-objective problem. sometimes, first half perform well in objective A, and second half perform well in objective B
2) most of the time, extreme points cannot dominate each other. making algorithm O(N), not O(lg N)

what should we do?
1) similar configuration indicates similar objective; i.e. I can ask my neighbor if I want to evaluate myself ( think about K-means)

2) model is a black box. BUT we know its monotonicity. 
(increase CPU/memory - > reduce time. increase $$)
there for, 
to estimate one objective, we can add delta to neighbor's obj.

to get delta,  see
![image](https://user-images.githubusercontent.com/3222148/29256241-b908c516-8076-11e7-92f9-35b87e99e0a3.png)

I tried to explain these in section 4.3

**Comment by ginfung** [comment]
unlike sway which is recursively pruning,
now we get all objective estimations first,
then non-dominate sorting.
