### ISSUE TITLE
Experiment 1 - without any optimization

### ISSUE THREAD

**Issue by ginfung** [ai-se/RIOT#3]
Problem description and related work -> wiki pages
if we don't use any optimization technique, simulate each workflow for 30 times. reporting the makespan
Lesson - The makespan can reduce at least 25% if task scheduled properly

![eprotein](https://cloud.githubusercontent.com/assets/3222148/25775350/174c6c08-3271-11e7-90e5-9b4a2af8f475.png)
![fmri](https://cloud.githubusercontent.com/assets/3222148/25775351/175e902c-3271-11e7-85cc-8f79264f16f9.png)
![j30](https://cloud.githubusercontent.com/assets/3222148/25775353/176743f2-3271-11e7-8b13-a988b4d6d2a0.png)
![j60](https://cloud.githubusercontent.com/assets/3222148/25775352/17673196-3271-11e7-94b1-58ba4bac58f1.png)
![j90](https://cloud.githubusercontent.com/assets/3222148/25775354/176775b6-3271-11e7-98a4-1773be8ab02f.png)

**Comment by timm** [comment]
good baselines
