### ISSUE TITLE
Experiment 3 :: SA vs. Static algorithm

### ISSUE THREAD

**Issue by ginfung** [ai-se/RIOT#5]
SA configurations:
- max iteration = 1000
- temperature reduce rate = 00.9

![eprotein](https://cloud.githubusercontent.com/assets/3222148/25881262/ec53e882-3509-11e7-9c00-149f149d29ac.png)
![fmri](https://cloud.githubusercontent.com/assets/3222148/25881264/ec5a90e2-3509-11e7-8e78-6f4daceb0054.png)
![j30](https://cloud.githubusercontent.com/assets/3222148/25881263/ec5a759e-3509-11e7-9064-43f8341ba653.png)
![j60](https://cloud.githubusercontent.com/assets/3222148/25881265/ec5e0c7c-3509-11e7-99a7-35a47b53e511.png)
![j90](https://cloud.githubusercontent.com/assets/3222148/25881266/ec5ed350-3509-11e7-9831-704349d99c05.png)

**Comment by timm** [comment]
ah- so i'm guessing that, soon, we will see

- on the LHS: some baseline showing the raw generation0 values (before treatment)
- underneath the dotted SA line
   - results for other optimizers

**Comment by ginfung** [comment]
Results moved to #6
