### ISSUE TITLE
Experiment 4: EMSC

### ISSUE THREAD

**Issue by ginfung** [ai-se/RIOT#9]
EMSC is a state-of-the-art meta-heuristic algorithm in solving workflow tradeoff balancing (cost & makespan).
MOHEFT is start-of-the-art heuristic algorithm before EMSC

![combine](https://user-images.githubusercontent.com/3222148/28399949-35fa1fea-6cde-11e7-9df4-5ded29adb2f8.png)

**Comment by timm** [comment]
ah. succinct charts. wonderful

- how does these methods compare on   SPREAD HV GD IGD?
- what are the runtimes?
- can we improve on the above with any of our tricks?

**Comment by timm** [comment]
as to the last point... what feature engineering is required to let us improve on the above with our tricks?

**Comment by ginfung** [comment]
@timm Runtime: column1<1min; column<2min; column3=30min; column=3h.
at arc clusters. 1/3 time in my macPro

spread. hv. gd. igd report later.

**Comment by ginfung** [comment]
@timm  I think **feature engineering <-> find a way to create better initial candidates in sway**. Your idea?
